### ISSUE TITLE
Page reloading, constanty

### ISSUE THREAD

**Issue by hyperoceanic** [laenas/laenas.github.io#2]
Hi - I'm trying to read https://laenas.github.io/posts/01-fs-primer.html but it keeps reloading. Whats with the web sockets? 

You've got some great content but I'm having to copy and paste it elsewhere to read it!

Kind regards
Mark Smith

**Comment by laenas** [comment]
What it sounds like is generic debug Fornax behavior - but it shouldn't be hitting on production and I'm not seeing similar.  Let me debug a bit and see if I can't figure out what's going on.

**Comment by hyperoceanic** [comment]
Hi Ryan -

01-fs-primer.html:8 WebSocket connection to 'ws://localhost:8080/websocket'
failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

init @ 01-fs-primer.html:8

Not having a websocket server is a possibility :-)

\m

**Comment by laenas** [comment]
Yep, it's Fornax behavior - live refresh when composing, that should get scrubbed for production.  :)

**Comment by laenas** [comment]
Should be sorted out now, thanks for the heads-up :)
